### ISSUE TITLE
Support for embedded Base64 images in JSON.

### ISSUE THREAD

**Issue by tk8817** [rajatthareja/ReportBuilder#2]
It would be great if you could embed the Base64 images which cucumber generates, into the HTML report. I would be happy to help with this as a pull request if you are unsure of how to implement. 

love the gem, it is great! 

``` json
           "keyword": "And ",
            "name": "I should not be logged in",
            "line": 58,
            "match": {
              "location": "features/step_defenitions/cnc_steps.rb:94"
            },
            "result": {
              "status": "skipped"
            }
          }
        ],
        "after": [
          {
            "match": {
              "location": "features/support/env.rb:85"
            },
            "result": {
              "status": "passed",
              "duration": 502779000
            },
            "embeddings": [
              {
                "mime_type": "image/png",
                "data": "iVBORw0KGgoAAAANSUhEUgAACQAAAAhKCAIAAABSiLKtAAAgAElEQVR4nOzdeZRcdZ03/s/33lv7XtVdVb2v6e50Z+1OAoEEDIZVZAQe9YePOM8TdXQeF5RRZkRxQBx1DnNcGJ2RUXl8DiOgI4PKaggRY0ggO1k6nd67el+q99rr3u/vj29SVKqrl3Q6IYT363g4ya273xzPvfd9P58vy8vLIwAAAAAAAAAAAAAAAICL69ChQ4wxp9PJGCMi8d95pc/GOc/
```

**Comment by rajatthareja** [comment]
Added support for embedding images.

**Comment by tk8817** [comment]
Hey @rajatthareja , here are the logs I get when trying to parse a JSON file which has images. I have uploaded the JSON file separatly. 

``` ruby 
JSON test report generated: 'report/historic/report_2016-02-10_15-54-34-764.json'
/Users/*******/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlmarkup.rb:281:in `write': "\x89" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlmarkup.rb:281:in `<<'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlmarkup.rb:281:in `_text'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:118:in `<<'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:305:in `block (2 levels) in build_embedding'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:300:in `block in build_embedding'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:294:in `each'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:294:in `build_embedding'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:225:in `block (2 levels) in build_scenario'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:222:in `each'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:222:in `block in build_scenario'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:215:in `build_scenario'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:147:in `block (8 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:147:in `each'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:147:in `block (7 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:146:in `block (6 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:145:in `block (5 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:139:in `each'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:139:in `each_with_index'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:139:in `block (4 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:138:in `block (3 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:137:in `block (2 levels) in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/jcommu/.gem/ruby/2.3.0/gems/builder-3.2.2/lib/builder/xmlbase.rb:93:in `method_missing'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:128:in `block in build_report'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:77:in `open'
	from /Users/jcommu/.gem/ruby/2.3.0/bundler/gems/ReportBuilder-15d33c9c4f6e/lib/report_builder.rb:77:in `build_report'
	from /Users/jcommu/Development/bueller_cnc/features/support/env.rb:100:in `block in <top (required)>'
```

**Comment by rajatthareja** [comment]
@tk8817 Could you share lines of code you are using for embedding image.

**Comment by tk8817** [comment]
@rajatthareja , it was an issue with my embed call - I have it working now :) . Closing this issue as the code you checked in is working perfectly.
