### ISSUE TITLE
Building HTML report fails when encountering output as Hash

### ISSUE THREAD

**Issue by sciros** [rajatthareja/ReportBuilder#25]
My JSON reports are slightly different from "typical" in that I add some additional information to them (via hooks). This information is added as a Hash (e.g. `puts [x:1, y:2]`) and the JSON formatter understands that just fine. Any post-processing of the JSON I do is merely augmented by this data and the default HTML formatter seems to handle it without issues, as well.

The report_builder script, however, appears to expect output added via `puts` to be text, and therefore chokes on a failed attempt to `.gsub(...)`. Not a big deal; I added an "unless output.is_a? Hash" for now because I don't care about that content being in the HTML report anyway. Any thoughts around what the preferred approach should be?

```
/Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:330:in `block in build_output': undefined method `gsub' for #<Hash:0x007fed5d170640> (NoMethodError)
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:329:in `each'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:329:in `build_output'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:294:in `block (2 levels) in build_scenario'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:293:in `each'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:293:in `block in build_scenario'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:286:in `build_scenario'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:206:in `block (8 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:206:in `each'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:206:in `block (7 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:205:in `block (6 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:204:in `block (5 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:198:in `each'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:198:in `each_with_index'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:198:in `block (4 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:197:in `block (3 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:195:in `block (2 levels) in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:175:in `_nested_structures'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:68:in `tag!'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/builder-3.2.2/lib/builder/xmlbase.rb:190:in `block (2 levels) in cache_method_call'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:186:in `block in build_report'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:115:in `open'
	from /Users/dsharkov/.rvm/gems/ruby-2.0.0-p643/gems/report_builder-0.1.2/lib/report_builder.rb:115:in `build_report'
	from scripts/report_builder.rb:12:in `<main>'

```

**Comment by sciros** [comment]
With newer Cucumber (2.2.0+) it stringifies anything passed to 'puts' (i.e. what makes it to output), so it won't ever encounter a Hash as long as the default JSON formatter is used. So this issue is probably moot at this point.
