### ISSUE TITLE
Unable to activate report_builder-0.1.2, because json-2.0.2 conflicts with json (>= 1.8.1, ~> 1.8) (Gem::ConflictError)

### ISSUE THREAD

**Issue by djangofan** [rajatthareja/ReportBuilder#34]
I just don't understand why I would get an error like this.   I created a project (on GitHub) that runs tests in parallel , wrapped by Rake+bundler  BUT when I try to run my project with just raw/bare cucumber, this is what I get...
I'm on Ubuntu 16.10.

```
superu@osboxes:~/Workspace/cuke-parallel-starter$ cucumber features --format progress
Unable to activate report_builder-0.1.2, because json-2.0.2 conflicts with json (>= 1.8.1, ~> 1.8) (Gem::ConflictError)
/home/superu/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/specification.rb:1408:in `activate'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems.rb:213:in `try_activate'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/home/superu/Workspace/cuke-parallel-starter/features/support/env.rb:4:in `<top (required)>'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/home/superu/.rbenv/versions/2.4.0/bin/cucumber:22:in `load'
/home/superu/.rbenv/versions/2.4.0/bin/cucumber:22:in `<main>'
superu@osboxes:~/Workspace/cuke-parallel-starter$ bundler exec cucumber -r features --format progress
Exception `NameError' at /home/superu/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/cucumber-2.4.0/lib/cucumber/constantize.rb:41 - uninitialized constant Cucumber::Formatter::Progress
Did you mean?  Process
.
Slept for 0.11357592786443138 milliseconds.
..
Slept for 0.18566912861453533 milliseconds.
..
```

**Comment by djangofan** [comment]
More info relating to my issue:
```
superu@osboxes:~/Workspace/cuke-parallel-starter$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    builder (3.2.3)
    cucumber (2.4.0)
      builder (>= 2.1.2)
      cucumber-core (~> 1.5.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      gherkin (~> 4.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.5.0)
      gherkin (~> 4.0)
    cucumber-wire (0.0.1)
    diff-lcs (1.3)
    gherkin (4.0.0)
    httparty (0.14.0)
      multi_xml (>= 0.5.2)
    json (1.8.6)
    multi_json (1.12.1)
    multi_test (0.1.2)
    multi_xml (0.6.0)
    parallel (1.11.0)
    parallel_cucumber (0.1.22)
      cucumber (~> 2)
      parallel (~> 1.6)
    rake (12.0.0)
    report_builder (0.1.2)
      builder (~> 3.2, >= 3.2.2)
      json (~> 1.8, >= 1.8.1)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)

PLATFORMS
  ruby
  x64-mingw32

DEPENDENCIES
  cucumber (>= 2.4.0)
  httparty
  parallel_cucumber
  rake
  report_builder
  rspec

BUNDLED WITH
   1.14.4

```

**Comment by Agezao** [comment]
Kinda old by now, but I get stucked on the same issue today.
I get it "fixed" by going on the gemspec for report_builder and forced it to run on ~> 2.0
\Ruby24-x64\lib\ruby\gems\2.4.0\specifications\report_builder-0.1.2.gemspec

Changed from:
`s.add_runtime_dependency(%q<json>.freeze, [">=1.8.1", "~> 1.8"])`

To:
`s.add_runtime_dependency(%q<json>.freeze, ["~> 2.0"])`

In every appearance of this line and everything start to work beautifully! :-)

**Comment by rajatthareja** [comment]
Working fine now. Hence closing.
